upstream event_service {
    server event-service:8001;
}
upstream ticket_service {
    server ticket-service:8002;
}
upstream payment_service {
    server payment-service:8003;
}
upstream booking_orchestrator {
    server booking-orchestrator:8004;
}

server {
    listen 80;
    server_name localhost;

    # Frontend SPA
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API routing
    location /api/events {
        proxy_pass http://event_service;
        rewrite ^/api/(.*) /$1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type";
    }

    location /api/tickets {
        proxy_pass http://ticket_service;
        rewrite ^/api/(.*) /$1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type";
    }

    location /api/payments {
        proxy_pass http://payment_service;
        rewrite ^/api/(.*) /$1 break;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type";
    }

    location /api/bookings {
        proxy_pass http://booking_orchestrator;
        rewrite ^/api/(.*) /$1 break;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type";
    }
}
